version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: bank_reviews_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword123
      - POSTGRES_DB=bank_reviews
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

